# Generated by Django 2.2.3 on 2019-07-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('issued_at', models.IntegerField()),
                ('data_access_expires_at', models.IntegerField()),
                ('token_expires_at', models.IntegerField()),
                ('scopes', models.TextField()),
            ],
        ),
    ]
